nelmio_cors:
  defaults:
    allow_origin:    ['http://127.0.0.1:8000']
    allow_methods:   ['POST','OPTIONS']
    allow_headers:   ['Content-Type']
    max_age:         3600
  paths:
    '^/tache/': ~
