vich_uploader:
    db_driver: orm
    mappings:
        evenement_images:
            uri_prefix: /uploads/evenements
            upload_destination: '%kernel.project_dir%/public/uploads/evenements'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            