version: '3.8'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

    mailhog:
        image: mailhog/mailhog
        ports:
            - "1025:1025"  # SMTP
            - "8025:8025"  # Web interface
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

