# config/services.yaml
parameters:
    photos_directory: '%kernel.project_dir%/public/uploads/images'
    services_directory: '%kernel.project_dir%/public/uploads/services'
    app.base_url: 'http://localhost:8000'
    stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'

services:
    # Default configuration for services
    _defaults:
        autowire: true
        autoconfigure: true

    # Stripe Service
    App\Service\StripeService:
        arguments:
            $stripeSecretKey: '%stripe_secret_key%'

    # Custom Command
    App\Command\GenerateEntitiesCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'

    # All classes in src/ except specified exclusions
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Command/'

    # Session Interface Alias
    Symfony\Component\HttpFoundation\Session\SessionInterface:
        alias: 'session'

    # Exchange Rate Service
    App\Service\ExchangeRateService:
        arguments:
            $httpClient: '@http_client'