# config/services.yaml
parameters:
    photos_directory: '%kernel.project_dir%/public/uploads/photos'
    services_directory: '%kernel.project_dir%/public/uploads/services'

    google_maps_api_key: 'AIzaSyD8Pz52O1TeGXsksJ7Pzbd-ayomxkR-IF0'
services:

    _defaults:
        autowire: true
        autoconfigure: true
    Psr\Log\LoggerInterface:
        alias: monolog.logger


    app.base_url: 'http://localhost:8000'
    stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
    app.brevo_api_key: '%env(BREVO_API_KEY)%'

    cvs_directory: '%kernel.project_dir%/public/uploads/cvs'



services:
    # Default configuration for services
    _defaults:
        autowire: true
        autoconfigure: true

    

    # Custom Command

    App\Command\GenerateEntitiesCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'

    # All classes in src/ except specified exclusions
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Command/'

    # Session Interface Alias
    Symfony\Component\HttpFoundation\Session\SessionInterface:
        alias: 'session'


    App\Service\BrevoService:
        arguments:
            $params: '@parameter_bag'
        tags: ['controller.service_arguments']

    App\Service\ExchangeRateService:
        arguments:
            $apiKey: '%env(EXCHANGE_RATES_API_KEY)%'


    App\Service\GeminiApiService:
        arguments:
            $apiKey: '%env(GEMINI_API_KEY)%'
            $apiUrl: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent'
            $logger: '@logger'

