# config/services.yaml
parameters:
    photos_directory: '%kernel.project_dir%/public/uploads/images'
    services_directory: '%kernel.project_dir%/public/uploads/services'
    app.base_url: 'http://localhost:8000'
    stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Command\GenerateEntitiesCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Command/' # Add this to exclude Commands from auto-registration

    Symfony\Component\HttpFoundation\Session\SessionInterface:
        alias: 'session'

    App\Service\ExchangeRateService:
        arguments:
            $httpClient: '@http_client'

    App\Service\StripeService:
        arguments:
            $params: '@parameter_bag'
            $serviceRepository: '@App\Repository\ServiceRepository'